{{- if .Values.mongo.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mongo.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "mongo.name" . }}
  replicas: {{ default 1 .Values.app.replicas | int }}
  template:
    metadata:
      labels:
        app: {{ include "mongo.name" . }}
    spec:
      containers:
      - name: mongo
        image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.mongo.image.pullPolicy }}
        ports:
        {{ range $key, $val := fromYaml (include "mongo.ports" .) -}}
        - name: {{ $key }}
          containerPort: {{ $val }}
        {{ end -}}
      {{- if .Values.mongo.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: /data/db
      volumes:
      - name: data
        emptyDir: {}
      volumeClaimTemplates:
      - metadata:
          name: data
        spec: {{ toYaml .Values.mongo.persistence.volumeClaimTemplateSpec | nindent 10 }}
      {{- end }}
    {{- if .Values.mongo.tolerations }}
      tolerations: {{ toYaml .Values.mongo.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.mongo.affinity }}
      affinity: {{ toYaml .Values.mongo.affinity | nindent 8 }}
    {{- end }}
    {{- if .Values.mongo.nodeSelector }}
      nodeSelector: {{ toYaml .Values.mongo.nodeSelector | nindent 8 }}
    {{- end }}
{{- if .Values.mongo.strategy }}
  strategy: {{ toYaml .Values.mongo.strategy | nindent 4 }}
{{- end }}
{{- end -}}