apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miner.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "miner.name" . }}
  replicas: {{ default 1 .Values.app.replicas | int }}
  template:
    metadata:
      labels:
        app: {{ include "miner.name" . }}
    spec:
      containers:
      - name: miner
        image: {{ include "miner.image" . }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.miner.image.pullPolicy }}
        ports:
        {{ range $key, $val := fromYaml (include "miner.ports" .) -}}
        - name: {{ $key }}
          containerPort: {{ $val }}
        {{ end -}}
        env:
        - name: HDX_NODE_ADVANCED_NETWORK_CAPTURE
          value: "1"
        - name: HYPERDX_LOG_LEVEL
          value: {{ default "debug" .Values.miner.logLevel }}
        - name: OTEL_LOG_LEVEL
          value: {{ default "debug" .Values.miner.logLevel }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ include "otel.exporter.otlp.endpoint" . }}
        - name: OTEL_SERVICE_NAME
          value: {{ include "miner.name" . }}
    {{- if .Values.miner.tolerations }}
      tolerations: {{ toYaml .Values.miner.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.miner.affinity }}
      affinity: {{ toYaml .Values.miner.affinity | nindent 8 }}
    {{- end }}
    {{- if .Values.miner.nodeSelector }}
      nodeSelector: {{ toYaml .Values.miner.nodeSelector | nindent 8 }}
    {{- end }}
{{- if .Values.miner.strategy }}
  strategy: {{ toYaml .Values.miner.strategy | nindent 4 }}
{{- end }}