apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "api.name" . }}
  replicas: {{ default 1 .Values.app.replicas | int }}
  template:
    metadata:
      labels:
        app: {{ include "api.name" . }}
    spec:
      containers:
      - name: api
        image: {{ include "api.image" . }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.api.image.pullPolicy }}
        ports:
        {{ range $key, $val := fromYaml (include "api.ports" .) -}}
        - name: {{ $key }}
          containerPort: {{ $val }}
        {{ end -}}
        envFrom:
        - secretRef:
            name: {{ include "api.secret.name" . }}
        env:
        - name: AGGREGATOR_API_URL
          value: {{ include "aggregator.api.url" . }}
        - name: APP_TYPE
          value: api
        - name: CLICKHOUSE_HOST
          value: {{ include "clickhouse.host" . }}
        - name: CLICKHOUSE_LOG_LEVEL
          value: trace
        - name: EXPRESS_SESSION_SECRET
          value: "hyperdx is cool"
        - name: FRONTEND_URL
          value: {{ include "frontend.url" . }} # need to be localhost (CORS)
        - name: HDX_NODE_ADVANCED_NETWORK_CAPTURE
          value: "1"
        - name: HDX_NODE_BETA_MODE
          value: "1"
        - name: HDX_NODE_CONSOLE_CAPTURE
          value: "1"
        - name: HYPERDX_LOG_LEVEL
          value: {{ default "debug" .Values.api.logLevel }}
        - name: INGESTOR_API_URL
          value: {{ include "ingestor.api.url" . }}
        - name: MINER_API_URL
          value: {{ include "miner.api.url" . }}
        - name: MONGO_URI
          value: {{ include "mongo.uri" . }}
        - name: NODE_ENV
          value: development
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ include "otel.exporter.otlp.endpoint" . }}
        - name: OTEL_SERVICE_NAME
          value: {{ include "api.name" . }}
        - name: PORT
          value: "{{ (fromYaml (include "api.ports" .)).api }}"
        - name: REDIS_URL
          value: {{ include "redis.url" . }}
        - name: SERVER_URL
          value: http://localhost:{{ (fromYaml (include "api.ports" .)).api }}
        - name: USAGE_STATS_ENABLED
          value: "false"