{{- if (and .Values.api.enabled .Values.api.clickhouseAuth.createSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.secret.name" . }}
type: Opaque
data:
  CLICKHOUSE_USERNAME: {{ .Values.api.clickhouseAuth.username | b64enc }}
  CLICKHOUSE_PASSWORD: {{ .Values.api.clickhouseAuth.password | b64enc }}
{{- end -}}
