{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.name" . }}
spec:
  selector:
    app: {{ include "api.name" . }}
  ports:
  {{ range $key, $val := fromYaml (include "api.ports" .) -}}
  - name: {{ $key }}
    port: {{ $val }}
  {{ end -}}
{{- end -}}