{{- if .Values.otelCollector.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otelCollector.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "otelCollector.name" . }}
  replicas: {{ default 1 .Values.app.replicas | int }}
  template:
    metadata:
      labels:
        app: {{ include "otelCollector.name" . }}
    spec:
      containers:
      - name: otel-collector
        image: {{ include "otelCollector.image" . }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.otelCollector.image.pullPolicy }}
        ports:
        {{ range $key, $val := fromYaml (include "otelCollector.ports" .) -}}
        - name: {{ $key }}
          containerPort: {{ $val }}
        {{ end -}}
        env:
        - name: HYPERDX_LOG_LEVEL
          value: {{ default "debug" .Values.otelCollector.logLevel }}
    {{- if .Values.otelCollector.tolerations }}
      tolerations: {{ toYaml .Values.otelCollector.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.otelCollector.affinity }}
      affinity: {{ toYaml .Values.otelCollector.affinity | nindent 8 }}
    {{- end }}
    {{- if .Values.otelCollector.nodeSelector }}
      nodeSelector: {{ toYaml .Values.otelCollector.nodeSelector | nindent 8 }}
    {{- end }}
{{- if .Values.otelCollector.strategy }}
  strategy: {{ toYaml .Values.otelCollector.strategy | nindent 4 }}
{{- end }}
{{- end -}}