{{- if (and .Values.clickhouse.enabled .Values.clickhouse.usersXML.createSecret) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "clickhouse.secret.name" . }}
stringData:
  users.xml: |
{{ tpl (.Files.Get "clickhouse/users.xml") . | indent 4 }}
{{- end -}}