apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "clickhouse.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "clickhouse.name" . }}
  replicas: {{ default 1 .Values.app.replicas | int }}
  template:
    metadata:
      labels:
        app: {{ include "clickhouse.name" . }}
    spec:
      containers:
      - name: clickhouse
        securityContext:
          capabilities:
            add: ["SYS_NICE", "NET_ADMIN", "IPC_LOCK"]
        image: "{{ .Values.clickhouse.image.repository }}:{{ .Values.clickhouse.image.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.clickhouse.image.pullPolicy }}
        ports:
        {{ range $key, $val := fromYaml (include "clickhouse.ports" .) -}}
        - name: {{ $key }}
          containerPort: {{ $val }}
        {{ end -}}
        env:
        - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
          value: "1"
        volumeMounts:
        - name: config
          mountPath: /etc/clickhouse-server/config.xml
          subPath: config.xml
        - name: users
          mountPath: /etc/clickhouse-server/users.xml
          subPath: users.xml
        {{- if .Values.clickhouse.persistence.enabled }}
        - name: data
          mountPath: /var/lib/clickhouse
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "clickhouse.configmap.name" . }}
          items:
          - key: config.xml
            path: config.xml
      - name: users
        secret:
          secretName: {{ include "clickhouse.secret.name" . }}
          items:
          - key: users.xml
            path: users.xml
      {{- if .Values.clickhouse.persistence.enabled }}
      - name: data
        emptyDir: {}
      volumeClaimTemplates:
      - metadata:
          name: data
        spec: {{ toYaml .Values.clickhouse.persistence.volumeClaimTemplateSpec | nindent 10 }}
      {{- end }}
    {{- if .Values.clickhouse.tolerations }}
      tolerations: {{ toYaml .Values.clickhouse.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.clickhouse.affinity }}
      affinity: {{ toYaml .Values.clickhouse.affinity | nindent 8 }}
    {{- end }}
    {{- if .Values.clickhouse.nodeSelector }}
      nodeSelector: {{ toYaml .Values.clickhouse.nodeSelector | nindent 8 }}
    {{- end }}
{{- if .Values.clickhouse.strategy }}
  strategy: {{ toYaml .Values.clickhouse.strategy | nindent 4 }}
{{- end }}