{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.name" . }}
  labels:
    app: {{ include "app.name" . }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "app.name" . }}
              port:
              {{ range $key, $val := fromYaml (include "app.ports" .) -}}
              {{ if eq $key "app" }}
                name: {{ $key }}
              {{ end -}}
              {{ end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}