{{- if .Values.app.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "app.name" . }}
  replicas: {{ default 1 .Values.app.replicas | int }}
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}
    spec:
      containers:
      - name: app
        image: {{ include "app.image" . }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.app.image.pullPolicy }}
        ports:
        {{ range $key, $val := fromYaml (include "app.ports" .) -}}
        - name: {{ $key }}
          containerPort: {{ $val }}
        {{ end -}}
        env:
        - name: PORT
          value: "{{ (fromYaml (include "app.ports" .)).app }}"
        - name: NODE_ENV
          value: development
    {{- if .Values.app.tolerations }}
      tolerations: {{ toYaml .Values.app.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.app.affinity }}
      affinity: {{ toYaml .Values.app.affinity | nindent 8 }}
    {{- end }}
    {{- if .Values.app.nodeSelector }}
      nodeSelector: {{ toYaml .Values.app.nodeSelector | nindent 8 }}
    {{- end }}
{{- if .Values.app.strategy }}
  strategy: {{ toYaml .Values.app.strategy | nindent 4 }}
{{- end }}
{{- end -}}