app:
  enabled: true
  replicas: 1
  image: {}
  #  repository: ghcr.io/hyperdxio/hyperdx
  #  tag: defaults to app-{{ .Chart.AppVersion }}
  #  pullPolicy: IfNotPresent
  #  pullSecret:
  # logLevel: debug
  # resources:
  # tolerations:
  # affinity:
  # nodeSelector:
  # strategy:


miner:
  enabled: true
  replicas: 1
  image: {}
  #  repository: ghcr.io/hyperdxio/hyperdx
  #  tag: defaults to miner-{{ .Chart.AppVersion }}
  #  pullPolicy: IfNotPresent
  #  pullSecret:
  # logLevel: debug
  # resources:
  # tolerations:
  # affinity:
  # nodeSelector:
  # strategy:

api:
  enabled: true
  replicas: 1
  image: {}
  #  repository: ghcr.io/hyperdxio/hyperdx
  #  tag: defaults to api-{{ .Chart.AppVersion }}
  #  pullPolicy: IfNotPresent
  #  pullSecret:
  # logLevel: debug
  clickhouseAuth:
    username: api
    password: api
    createSecret: true
    # secretName:
  # resources:
  # tolerations:
  # affinity:
  # nodeSelector:
  # strategy:

taskCheckAlerts:
  enabled: true
  replicas: 1
  image: {}
  #  repository: ghcr.io/hyperdxio/hyperdx
  #  tag: defaults to api-{{ .Chart.AppVersion }}
  #  pullPolicy: IfNotPresent
  #  pullSecret:
  clickhouseAuth:
    username: worker
    password: worker
    createSecret: true
    # secretName:
  # resources:
  # tolerations:
  # affinity:
  # nodeSelector:
  # strategy:

ingestor:
  enabled: true
  replicas: 1
  image: {}
  #  repository: ghcr.io/hyperdxio/hyperdx
  #  tag: defaults to ingestor-{{ .Chart.AppVersion }}
  #  pullPolicy: IfNotPresent
  #  pullSecret:
  # logLevel: debug
  # resources:
  # tolerations:
  # affinity:
  # nodeSelector:
  # strategy:

otelCollector:
  enabled: true
  replicas: 1
  image: {}
  #   repository: ghcr.io/hyperdxio/hyperdx
  #   tag: defaults to otel-collector-{{ .Chart.AppVersion }}
  #   pullPolicy: IfNotPresent
  #   pullSecret:
  # logLevel: debug
  # resources:
  # tolerations:
  # affinity:
  # nodeSelector:
  # strategy:

hostmetrics:
  enabled: true
  replicas: 1
  image: {}
  #   repository: ghcr.io/hyperdxio/hyperdx
  #   tag: defaults to hostmetrics-{{ .Chart.AppVersion }}
  #   pullPolicy: IfNotPresent
  #   pullSecret:
  # logLevel: debug
  # resources:
  # tolerations:
  # affinity:
  # nodeSelector:
  # strategy:

aggregator:
  enabled: true
  replicas: 1
  image: {}
  #   repository: ghcr.io/hyperdxio/hyperdx
  #   tag: defaults to api-{{ .Chart.AppVersion }}
  #   pullPolicy: IfNotPresent
  #   pullSecret:
  # logLevel: debug
  clickhouseAuth:
    username: aggregator
    password: aggregator
    createSecret: true
    # secretName:
  # resources:
  # tolerations:
  # affinity:
  # nodeSelector:
  # strategy:

clickhouse:
  enabled: true
  replicas: 1
  image:
    repository: clickhouse/clickhouse-server
    tag: 23.7.1-alpine
    # pullPolicy: IfNotPresent
    # pullSecret:
  # logLevel: debug
  persistence:
    enabled: false
    volumeClaimTemplateSpec: {}
    #  storageClassName: gp3
    #  accessModes: ["ReadWriteOnce"]
    #  resources:
    #    requests: 5Gi
  # resources:
  # tolerations:
  # affinity:
  # nodeSelector:
  # strategy:

mongo:
  enabled: true
  replicas: 1
  image:
    repository: mongo
    tag: 5.0.14-focal
    # pullPolicy: IfNotPresent
    # pullSecret:
  persistence:
    enabled: false
    volumeClaimTemplateSpec: {}
    #  stroageClassName: gp3
    #  accessModes: ["ReadWriteOnce"]
    #  resources:
    #    requests: 5Gi
  # resources:
  # tolerations:
  # affinity:
  # nodeSelector:
  # strategy:

redis:
  enabled: true
  replicas: 1
  image:
    repository: redis
    tag: 7.0.11-alpine
    # pullPolicy: IfNotPresent
    # pullSecret:
  persistence:
    enabled: false
    volumeClaimTemplateSpec: {}
    #  stroageClassName: gp3
    #  accessModes: ["ReadWriteOnce"]
    #  resources:
    #    requests: 5Gi
  # resources:
  # tolerations:
  # affinity:
  # nodeSelector:
  # strategy:

ingress:
  enabled: false
  # hostname:
  # tls:
