{{- if (and .Values.aggregator.enabled .Values.aggregator.clickhouseAuth.createSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aggregator.secret.name" . }}
type: Opaque
data:
  CLICKHOUSE_USERNAME: {{ .Values.aggregator.clickhouseAuth.username | b64enc }}
  CLICKHOUSE_PASSWORD: {{ .Values.aggregator.clickhouseAuth.password | b64enc }}
{{- end -}}
