{{- if (and .Values.taskCheckAlerts.enabled .Values.taskCheckAlerts.clickhouseAuth.createSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskCheckAlerts.secret.name" . }}
type: Opaque
data:
  CLICKHOUSE_USERNAME: {{ .Values.taskCheckAlerts.clickhouseAuth.username | b64enc }}
  CLICKHOUSE_PASSWORD: {{ .Values.taskCheckAlerts.clickhouseAuth.password | b64enc }}
{{- end -}}
