apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hostmetrics.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "hostmetrics.name" . }}
  replicas: {{ default 1 .Values.app.replicas | int }}
  template:
    metadata:
      labels:
        app: {{ include "hostmetrics.name" . }}
    spec:
      containers:
      - name: hostmetrics
        image: {{ include "hostmetrics.image" . }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.hostmetrics.image.pullPolicy }}
        env:
        - name: HYPERDX_LOG_LEVEL
          value: {{ default "debug" .Values.hostmetrics.logLevel }}
        - name: OTEL_SERVICE_NAME
          value: {{ include "miner.name" . }}
    {{- if .Values.hostmetrics.tolerations }}
      tolerations: {{ toYaml .Values.hostmetrics.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.hostmetrics.affinity }}
      affinity: {{ toYaml .Values.hostmetrics.affinity | nindent 8 }}
    {{- end }}
    {{- if .Values.hostmetrics.nodeSelector }}
      nodeSelector: {{ toYaml .Values.hostmetrics.nodeSelector | nindent 8 }}
    {{- end }}
{{- if .Values.hostmetrics.strategy }}
  strategy: {{ toYaml .Values.hostmetrics.strategy | nindent 4 }}
{{- end }}